### ISSUE TITLE
Definicao complementada de CNS (constante) 

### ISSUE THREAD

**Issue by HenriqueFT** [ChristianoBraga/PiFramework#5]
-Em Pi-in-a-nutshell apenas existe uma referencia a **CNS** sendo o OPCode **#CNS** , porem nenhuma definicao da funcao delta deste e dele na gramatica.

-Existem duas regras VAR no pi-denotation

-Padronizar para a palavra CONST

**Comment by ChristianoBraga** [comment]
Obrigado!
